name: Generate metrics

on:
  schedule:
    - cron: "0 2 * * *" # maj quotidienne à 02:00 UTC
  workflow_dispatch: # exécuter manuellement depuis l’onglet Actions
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build metrics
        uses: lowlighter/metrics@latest
        with:
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris

          # Token : si tu veux les contributions privées, mets METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}

          # Plugins proches de ta capture
          plugin_languages: yes
          plugin_languages.limit: 8
          plugin_languages.sections: most-used

          plugin_isocalendar: yes
          plugin_isocalendar.duration: half-year # grille de contributions

          plugin_topics: yes
          plugin_topics.mode: starred
          plugin_topics.limit: 12

          plugin_repositories: yes
          plugin_repositories.batch: 100

          # (optionnel) autres modules utiles
          plugin_achievements: yes
          plugin_stars: no
          plugin_followup: no

      - name: Commit generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -f "github-metrics.svg" ]; then
            git add github-metrics.svg
            git commit -m "chore: update metrics" || echo "No changes"
            git push
          fi
